"use strict";
// Standalone concept interaction only; this file does not load or change game saves.
const query=new URLSearchParams(location.search);
const concept=query.get('concept')==='06-rootvault-workshop'?'06-rootvault-workshop':'05-kernel-foundry';
const isFoundry=concept==='05-kernel-foundry';
const validScreens=new Set(['title','play','setup','character','academy','lesson','map','battle','library','settings','profile','pause','draft','reward','rest','results','help','deck']);
let screen=validScreens.has(query.get('screen'))?query.get('screen'):'title';
let skin='copper',chosen='copper',selectedMode='Shardrun',selectedRoom='Foundry gate',settingCategory='General';
const history=[];
const storageKey='rootward-underground-concept-skin-'+concept;
if(query.get('capture')!=='1'){try{const saved=localStorage.getItem(storageKey);if(Draw.skins.some(s=>s.id===saved))skin=chosen=saved;}catch{}}
const viewport=document.getElementById('viewport');
const assets='../../game/assets/shardrun/';
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,destination,classes='',icon='')=>`<button class="button ${classes}" data-go="${destination}">${icon?Draw.icon(icon):''}${text}</button>`;
const crumb=(chapter)=>`<div class="crumb">${btn('Back','back','quiet','back')}<span>${chapter}</span></div>`;
const skinName=()=>Draw.skins.find(s=>s.id===skin).name;
function nav(){const active=['setup','draft'].includes(screen)?'play':screen;
let items=[['Play','play','play'],['Academy','academy','academy'],['Library','library','library'],['Character','character','character']];
const globalNav=isFoundry?`<nav class="dock" aria-label="Main navigation">${screen==='title'?'':btn('Home','title','quiet','home')}${items.filter(x=>screen!=='title'||['library','character'].includes(x[1])).map(([n,d,i])=>btn(n,d,active===d?'selected':'quiet',i)).join('')}${btn('Settings','settings',active==='settings'?'selected':'quiet','settings')}</nav>`:`<div class="brand-mini">${btn('<span class="logo small">ROOTWARD</span>','title','quiet')}</div><nav class="command" aria-label="Main navigation">${items.map(([n,d,i])=>btn(n,d,active===d?'selected':'quiet',i)).join('')}</nav>`;
return globalNav+`<div class="utility">${btn('Mira','profile','quiet','profile')}${!isFoundry?btn('Settings','settings','quiet','settings'):''}<span class="language subtle">EN / 日本語</span>${btn('Quit','quit','quiet','quit')}</div>`;}
function title(){return isFoundry?`<section class="title-left"><div class="eyebrow">The surface station</div><h1 class="logo">ROOTWARD</h1><p class="subtle">Program the spell.<br>Descend into the machine.</p><div class="resume">${btn('Resume descent','map','primary','down')}<div class="saved-note">Shardrun · The Heap · Python</div></div><div class="launch">${btn('Play','play','primary','play')}${btn('Academy','academy','','academy')}</div></section><div class="title-note">SALVAGE → HEAP → KERNEL</div>`:`<section class="dispatch"><div class="eyebrow">Your next step</div><h2>The Heap</h2><p class="subtle">Layer 02 · Shardrun<br>Vesper · ${skinName()}</p>${btn('Resume descent','map','primary','down')}<div class="saved-note">Begin at the surface ${btn('New run','play','quiet')}</div></section><div class="positioned" style="left:90px;top:202px"><div class="eyebrow">Beneath the surface</div><h1 style="font-size:35px;font-weight:400;line-height:1.5">Build a spell.<br>Find your way down.</h1></div>`;}
function play(){return `<section class="page panel accent">${crumb('Play')}<div class="eyebrow">Choose your descent</div><h2>A journey of your own</h2><div class="mode-options" style="margin-top:25px">${[['Shardrun','play'],['Spellforge','forge'],['Academy','academy']].map(([n,i])=>`<button class="button ${selectedMode===n?'selected':''}" data-mode="${n}">${Draw.icon(i)}${n}</button>`).join('')}</div><p class="mode-description">${selectedMode==='Shardrun'?'Draft algorithm shards. Build your program in order. Descend through the layers.':selectedMode==='Spellforge'?'Assemble and test your own spells at the workbench, then take them below.':'Learn programming at your own pace. Read, trace, test, and write real code.'}</p><div class="row spread">${btn(selectedMode==='Academy'?'Open Academy':'Start a new run',selectedMode==='Academy'?'academy':'setup','primary','down')}${selectedMode==='Shardrun'?btn('Continue saved run','map','quiet'):''}</div></section>`;}
function setup(){return `<section class="page panel accent">${crumb('Play / '+selectedMode)}<h2>Prepare your descent</h2><div class="form-row"><label for="language">Language</label><select id="language"><option>Python</option><option>JavaScript</option></select></div><div class="form-row"><label for="difficulty">Challenge</label><select id="difficulty"><option>Beginner</option><option>Programmer</option></select></div><div class="form-row"><span>Character</span><span class="subtle">Vesper · ${skinName()}</span></div><div class="rule"></div><div class="row spread"><span class="fine">Skin follows your local profile.</span>${btn('Begin descent','draft','primary','down')}</div></section>`;}
function character(){return `<section class="skin-page panel">${crumb('Character / Skins')}<div class="eyebrow">Vesper</div><h2>Choose your appearance</h2><p class="subtle" style="margin-top:12px">One character. A look that stays with you.</p><div class="skin-list">${Draw.skins.map(s=>`<button class="skin-card ${chosen===s.id?'selected':''}" data-skin="${s.id}" aria-pressed="${chosen===s.id}">${Draw.puppet(s.id,true)}<div><h3>${s.name}</h3><p>${s.id===skin?'Current skin':s.detail}</p></div></button>`).join('')}</div><div class="skin-actions"><span class="skin-status">${Draw.icon('check')}${chosen===skin?'Current skin selected':'Previewing appearance'}</span><button class="button primary" data-action="use-skin">Use this skin</button></div><p class="fine" style="margin-top:18px">Used across menus and journeys. Cosmetic only.</p></section><div class="actor-caption"><h3>Vesper</h3><p>${Draw.skins.find(s=>s.id===chosen).name}</p></div>`;}
function academy(){const nodes=[['Variables',110,30],['Conditions',395,50],['Loops',70,180],['Lists',390,200],['Functions',230,325]];
return `<header class="section-heading"><div class="eyebrow">Academy</div><h1>Learn at the workbench</h1><p class="subtle">Small ideas. Real code. Your own pace.</p></header><div class="academy-map"><svg width="715" height="395" style="position:absolute;inset:0" aria-hidden="true"><path d="M196 60L478 80L472 230L142 210L312 353L472 230" fill="none" stroke="#6f5e46" stroke-width="2"/><path d="M196 60L142 210L472 230" fill="none" stroke="#f2a541" stroke-width="2"/></svg>${nodes.map(([n,x,y])=>`<button class="concept-node ${n==='Lists'?'current':''}" style="left:${x}px;top:${y}px" data-go="lesson">${n==='Variables'||n==='Loops'?Draw.icon('check'):''}${n}</button>`).join('')}</div><section class="academy-page panel"><div class="eyebrow">Continue learning · Lists</div><h2>Count the even numbers</h2><p class="subtle" style="margin-top:15px">Use a loop and a condition to count matching items in a list.</p><div class="tabs"><button class="button selected" data-language="Python">Python</button><button class="button" data-language="JavaScript">JavaScript</button></div><div class="row spread">${btn('Continue lesson','lesson','primary','arrow')}<span class="fine">Lesson 3 of 5</span></div><div class="rule"></div><p class="fine">Read & Trace · Practice · Learning journal</p></section>`;}
function lesson(){return `<section class="page panel" style="width:885px;left:${isFoundry?'410':'535'}px;top:226px">${crumb('Academy / Lists')}<h2>Count the even numbers</h2><p class="subtle" style="margin-top:16px">Write a function that counts even numbers in a list.<br>Consider what should happen with an empty list.</p><div class="tabs"><button class="button selected" data-language="Python">Python</button><button class="button" data-language="JavaScript">JavaScript</button></div><pre class="code"><span class="keyword">def</span> count_even(values):
    <span class="comment"># TODO: write your solution</span>


</pre><div class="row spread" style="margin-top:24px"><button class="button primary" data-action="test-lesson">Run tests</button><button class="button" data-action="hint">Hint</button></div></section>`;}
const roomsFoundry=[{x:813,y:181,kind:'fight',name:'Surface',state:'visited'},{x:642,y:325,kind:'cache',name:'The Salvage',state:'visited'},{x:976,y:325,kind:'fight',name:'Scrap gallery',state:''},{x:480,y:479,kind:'rest',name:'Quiet bay',state:''},{x:812,y:479,kind:'fight',name:'Current room',state:'current'},{x:1141,y:479,kind:'forge',name:'Old workshop',state:''},{x:634,y:640,kind:'fight',name:'Foundry gate',state:'available'},{x:978,y:640,kind:'cache',name:'Brass vault',state:'available'},{x:480,y:802,kind:'rest',name:'Shelter',state:''},{x:813,y:802,kind:'forge',name:'Root forge',state:''},{x:1141,y:802,kind:'fight',name:'Lower galleries',state:''},{x:813,y:956,kind:'guardian',name:'Kernel guardian',state:'guardian'}];
const edgesFoundry=[[0,1],[0,2],[1,3],[1,4],[2,4],[2,5],[3,6],[4,6],[4,7],[5,7],[6,8],[6,9],[7,9],[7,10],[8,11],[9,11],[10,11]];
const roomsWorkshop=[{x:402,y:228,kind:'fight',name:'Surface',state:'visited'},{x:587,y:330,kind:'cache',name:'The Salvage',state:'visited'},{x:814,y:320,kind:'rest',name:'Lamp room',state:''},{x:638,y:498,kind:'fight',name:'Current room',state:'current'},{x:1085,y:546,kind:'forge',name:'Copper workbench',state:'available'},{x:887,y:654,kind:'fight',name:'Foundry gate',state:'available'},{x:1235,y:688,kind:'cache',name:'Buried library',state:''},{x:1040,y:807,kind:'rest',name:'Deep shelter',state:''},{x:1470,y:820,kind:'fight',name:'Lower galleries',state:''},{x:1180,y:991,kind:'guardian',name:'Kernel guardian',state:'guardian'}];
const edgesWorkshop=[[0,1],[0,2],[1,3],[2,3],[2,4],[3,4],[3,5],[4,6],[5,6],[5,7],[6,8],[7,9],[8,9]];
function map(){const rooms=isFoundry?roomsFoundry:roomsWorkshop,edges=isFoundry?edgesFoundry:edgesWorkshop;const activeEdges=isFoundry?[0,3,7]:[0,2,6];
return `<header class="map-heading"><h1 class="logo">SHARDRUN</h1><p class="subtle">The Heap · Layer 02 · ${skinName()}</p></header><div class="utility">${btn('Deck','deck','quiet','library')}${btn('Stats','results','quiet')}${btn('Menu','pause','quiet','settings')}</div>${isFoundry?'<aside class="depth-key"><div><strong>01 · Salvage</strong>Upper galleries</div><div class="active"><strong>02 · Heap</strong>You are here</div><div><strong>03 · Kernel</strong>Below the foundations</div></aside>':''}<svg class="route-map" viewBox="0 0 1920 1080" aria-hidden="true">${edges.map(([a,b],i)=>`<path d="M${rooms[a].x} ${rooms[a].y}L${rooms[b].x} ${rooms[b].y}" fill="none" stroke="${activeEdges.includes(i)?'#f2a541':'#6f5e46'}" stroke-width="${activeEdges.includes(i)?3:1.5}" opacity="${activeEdges.includes(i)?1:.5}"/>`).join('')}</svg>${rooms.map(r=>`<button class="room ${r.state}" style="left:${r.x}px;top:${r.y}px" data-room="${r.name}" aria-label="${r.name}, ${r.kind}">${Draw.icon(r.kind)}<span class="room-name">${r.name}</span></button>`).join('')}<section class="encounter panel"><div class="eyebrow">Next chamber ↓</div><h2>${safe(selectedRoom)}</h2><p class="subtle">A warm-lit gate beneath the workbench.<br>Fight · Tally Wisp</p>${btn('Enter chamber','battle','primary','down')}</section><div class="down-note">${Draw.icon('down')}Deeper toward the Kernel</div><div class="map-legend">${[['fight','Fight'],['forge','Forge'],['rest','Rest'],['cache','Cache'],['guardian','Guardian']].map(([i,n])=>`<span>${Draw.icon(i)}${n}</span>`).join('')}</div>`;}
const shardData=[['knapsack-strike','Knapsack Strike','Choose a set of strikes.','STRIKE',1,'O(n)'],['charge','Charge','Adds power to your bolts.','SHAPE',0,'O(1)'],['round-robin','Round Robin','Share the work in order.','SHAPE',1,'O(n)'],['amplify','Amplify','Multiply each bolt’s power.','SHAPE',0,'O(n)'],['chill','Chill','Turn bolts into frost.','SHAPE',0,'O(n)'],['salvo','Salvo','Release your stored bolts.','SOURCE',1,'O(n)']];
function card(s){return `<div class="shard-card"><span class="cost">${s[4]}</span><span class="complexity">${s[5]}</span><img src="${assets}card-${s[0]}.png" alt=""><h3>${s[1]}</h3><p>${s[2]}</p><span class="type">${s[3]}</span></div>`;}
function battle(){return `<header class="run-header"><div class="row"><strong>SHARDRUN</strong><span class="gold">ITERATION</span><span class="subtle">Turn 1 · The Heap</span></div><div class="row"><span class="subtle">Integrity <span class="meter"><i></i></span>48 / 60</span>${btn('Deck','deck','quiet')}${btn('Stats','results','quiet')}${btn('Menu','pause','','settings')}</div></header><div class="arena-caption">${isFoundry?'THE LOWER FOUNDRY':'THE ROOT VAULT'}</div><section class="hero-info"><h3>Vesper</h3><div class="unit-health"><i></i></div><span class="subtle">48 / 60</span><span style="float:right;color:var(--violet)">◆ ◆ ◆ 3 / 5</span></section><section class="foe-info"><h3>${isFoundry?'Tally Wisp':'Heap Guardian'}</h3><div class="unit-health"><i style="width:72%"></i></div><span class="subtle">24 / 33</span><div class="foe-intent">${Draw.icon('fight')}Strike for 4 · 28 ops</div></section><section class="battle-desk"><div class="portrait-column">${Draw.puppet(skin,true)}<h3>VESPER</h3>${btn('End turn','reward','primary')}<button class="button quiet" data-action="log">Combat log</button></div><div class="program-table"><div class="spell-row"><div><div class="fine" style="margin-bottom:10px">Your program · main.js</div><div class="slots">${['charge','amplify','salvo','',''].map((s,i)=>`<div class="slot ${s?'filled':''}">${s?`<img src="${assets}card-${s}.png" alt="">${s[0].toUpperCase()+s.slice(1)}`:'slot '+(i+1)}</div>`).join('')}</div></div><div class="program-summary"><span class="gold">3 shards · 9 damage</span><span class="fine">Build in the order they run.</span><button class="button primary" data-action="preview-program">${Draw.icon('play')}Run program</button></div></div><div class="hand-row"><div class="pile"><img src="../../game/assets/brand/shardrun.png" alt="">Draw · 12</div><div class="hand">${shardData.map(card).join('')}</div><div class="hold">Hold</div><div class="pile"><img src="../../game/assets/brand/shardrun.png" alt="">Discard · 3</div></div></div><section class="code-pane"><div class="row spread"><h3>main.js</h3><span class="teal">O(n)</span><span class="fine">0 / 4096 ops</span></div><div class="race"><span>▼ foe tempo · 28 ops</span></div><pre class="code"><span class="comment">1  // Your shards build this program.</span>
2  <span class="keyword">function</span> program(battle) {
3      <span class="comment">// Charge → Amplify → Salvo</span>
4      <span class="comment">// Open a shard to read its code.</span>
5  }
</pre><div class="rule"></div><p class="fine">Preview shows measured work.<br>Cast uses the same program.</p><div class="row" style="margin-top:20px"><button class="button" data-action="preview-program">Preview</button><button class="button primary" data-action="cast-program">Cast</button></div></section></section>`;}
function utilityPage(title,body){return `<section class="utility-page panel">${crumb(title)}<h2>${title}</h2>${body}</section>`;}
function library(){return utilityPage('Library',`<div class="tabs">${['Cards','Relics','Foes','Concepts'].map((t,i)=>`<button class="button ${i===0?'selected':''}" data-library="${t}">${t}</button>`).join('')}</div><div class="library-items">${shardData.slice(0,4).map(s=>`<button class="entry" data-action="inspect"><img src="${assets}card-${s[0]}.png" alt=""><span>${s[1]}</span></button>`).join('')}</div><div class="rule"></div><div class="row spread"><span class="fine">Page 1 of 8</span><button class="button quiet" data-action="next-library">Next →</button></div>`);}
function settings(){return utilityPage('Settings',`<div class="tabs">${['General','Audio','Display','Access'].map(t=>`<button class="button ${settingCategory===t?'selected':''}" data-category="${t}">${t}</button>`).join('')}</div>${settingCategory==='Audio'?'<label class="settings-row">Music <input type="range" value="65" aria-label="Music volume"></label><label class="settings-row">Effects <input type="range" value="75" aria-label="Effects volume"></label>':settingCategory==='Display'?'<label class="settings-row">Window mode <select><option>Windowed</option><option>Fullscreen</option></select></label><label class="settings-row">UI scale <select><option>100%</option><option>125%</option></select></label>':'<label class="settings-row">Text size <select><option>Standard</option><option>Large</option></select></label><label class="settings-row">Reduced motion <input type="checkbox" checked></label><label class="settings-row">Show code hints <input type="checkbox" checked></label>'}<div class="rule"></div>${btn('Close','back','primary')}`);}
function profile(){return utilityPage('Local profiles',`<p class="subtle" style="margin:18px 0">Language, learning progress, and appearance stay with your profile.</p>${['Mira · Python · Current','Hana · JavaScript','New profile'].map(n=>`<button class="entry" data-action="profile">${Draw.icon('profile')}${n}</button>`).join('')}<p class="fine" style="margin-top:24px">Current skin · ${skinName()}</p>`);}
function pause(){return `<div class="overlay-dim"></div><section class="pause-page panel accent"><div class="eyebrow">Shardrun · paused</div><h2>Take a breath</h2>${btn('Resume','battle','primary','play')}${btn('Settings','settings','','settings')}${btn('Save & return','title','','home')}<button class="button danger" data-action="abandon">Abandon run</button></section>`;}
function draft(){return utilityPage('Choose a paradigm',`<p class="subtle" style="margin-top:18px">A way to approach your program.</p><div class="tabs">${['Iteration','Recursion','Search'].map((t,i)=>`<button class="button ${i===0?'selected':''}" data-paradigm="${t}">${t}</button>`).join('')}</div><p class="subtle">Iteration · repeat small steps to build momentum.</p><div class="rule"></div>${btn('Begin descent','map','primary','down')}`);}
function reward(){return utilityPage('Choose a reward',`<div class="mini-cards">${shardData.slice(1,4).map(card).join('')}</div><div class="row">${btn('Take selected shard','map','primary')}${btn('Skip','map','quiet')}</div>`);}
function rest(){return utilityPage('A quiet chamber',`<p class="subtle" style="margin-top:16px">A lantern burns beside an old workbench.</p><div class="stack" style="margin-top:25px">${btn('Rest','map','','rest')}${btn('Reforge a shard','reward','','forge')}${btn('Leave','map','primary','down')}</div>`);}
function results(){return utilityPage('Your descent',`<p class="subtle" style="margin-top:20px">The Heap · Iteration · Python</p><div class="results-stats"><div><strong>12</strong><span>Chambers</span></div><div><strong>28</strong><span>Measured work</span></div><div><strong>3</strong><span>Relics</span></div></div><div class="row">${btn('Run history','profile','quiet')}${btn('Return home','title','primary','home')}</div>`);}
function help(){return utilityPage('How to play',`<div class="tabs"><span class="tag">1 · Build</span><span class="tag">2 · Preview</span><span class="tag">3 · Cast</span></div><p class="subtle">Place shards in your program in the order they should run. Read their code. Preview the measured result before casting.</p><div class="rule"></div>${btn('Try Shardrun','battle','primary')}`);}
function deck(){return utilityPage('Your deck',`<div class="tabs"><span class="tag">Deck · 13</span><span class="tag">Relics · 3</span><span class="tag">Stats</span></div><div class="library-items">${shardData.slice(0,4).map(s=>`<div class="entry"><img src="${assets}card-${s[0]}.png" alt="">${s[1]}</div>`).join('')}</div><div class="rule"></div>${btn('Return to run','back','primary')}`);}
const renderers={title,play,setup,character,academy,lesson,map,battle,library,settings,profile,pause,draft,reward,rest,results,help,deck};
function render(){const sceneScreen=screen==='pause'?'battle':screen;viewport.className=isFoundry?'foundry':'workshop';viewport.innerHTML=Draw.scene(concept,sceneScreen,screen==='character'?chosen:skin)+`<div class="content">${['map','battle','pause'].includes(screen)?'':nav()}${renderers[screen]()}${['title','play','character','academy'].includes(screen)?'<div class="footer-hint">Tab / arrows · Select &nbsp; Esc · Back</div>':''}</div>`;document.title=`Rootward · ${isFoundry?'Kernel Foundry':'Rootvault Workshop'} · ${screen}`;fit();}
function fit(){const scale=Math.min(innerWidth/1920,innerHeight/1080);viewport.style.transform=`scale(${scale})`;viewport.style.left=(innerWidth-1920*scale)/2+'px';viewport.style.top=(innerHeight-1080*scale)/2+'px';}
function toast(message){document.querySelector('.toast')?.remove();const box=document.createElement('div');box.className='toast';box.setAttribute('role','status');box.textContent=message;viewport.append(box);setTimeout(()=>box.remove(),4000);}
function go(next){if(next==='quit'){toast('Close this preview tab to quit.');return;}if(next==='back'){next=history.pop()||'title';}else if(validScreens.has(next)&&next!==screen){history.push(screen);}if(!validScreens.has(next))return;screen=next;render();}
viewport.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;
if(target.dataset.go){go(target.dataset.go);return;}
if(target.dataset.skin){chosen=target.dataset.skin;render();return;}
if(target.dataset.mode){selectedMode=target.dataset.mode;render();return;}
if(target.dataset.room){const rooms=isFoundry?roomsFoundry:roomsWorkshop;const room=rooms.find(r=>r.name===target.dataset.room);if(room.state==='available'){selectedRoom=room.name;render();}else toast(room.state==='current'?'You are here.':'Continue downward to reach this chamber.');return;}
if(target.dataset.category){settingCategory=target.dataset.category;render();return;}
if(target.dataset.language||target.dataset.library||target.dataset.paradigm){for(const b of target.parentElement.children)b.classList.remove('selected');target.classList.add('selected');return;}
if(target.dataset.action==='use-skin'){skin=chosen;try{localStorage.setItem(storageKey,skin);}catch{}render();toast('Appearance saved for this preview profile.');return;}
const messages={'test-lesson':'Lesson workspace preview. No learner code runs here.','hint':'What should your count start at?','preview-program':'Preview area: measured work and damage appear here.','cast-program':'Battle layout preview. Combat runs in the game.','log':'The combat log opens beside the code pane.','inspect':'A short inspector opens for the selected card.','profile':'Local profile selector preview.','next-library':'The next catalogue page would open here.','abandon':'Abandon this run? The implementation will ask for confirmation.'};if(messages[target.dataset.action])toast(messages[target.dataset.action]);
});
addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();go('back');}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){const buttons=Array.from(viewport.querySelectorAll('button:not(:disabled)'));const index=buttons.indexOf(document.activeElement);event.preventDefault();buttons[(index+(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1)+buttons.length)%buttons.length]?.focus();}});
addEventListener('resize',fit);render();
